name: DevSecOps CI

on:
  push:
    branches:
      - develop
      - feature/cicd-security

  pull_request:
    branches:
      - develop
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --ignore-scripts    

      - name: Show Node and npm versions
        run: |
          node --version
          npm --version